/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/clusters/{collection}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Clusters
         * @description Paginated cluster list with quality metadata.
         */
        get: operations["list_clusters_api_clusters__collection__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clusters/{collection}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cluster Stats
         * @description Aggregate cluster statistics for a collection.
         */
        get: operations["cluster_stats_api_clusters__collection__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clusters/{collection}/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cluster Detail
         * @description Full cluster detail with member documents.
         */
        get: operations["cluster_detail_api_clusters__collection___key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clusters/{collection}/{key}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cluster Graph
         * @description Return nodes and edges for cluster visualization.
         */
        get: operations["cluster_graph_api_clusters__collection___key__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Collections
         * @description List all non-system collections with name, type, and count.
         */
        get: operations["list_collections_api_collections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections/{name}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profile Collection
         * @description Profile a collection's fields for ER-relevant statistics.
         */
        get: operations["profile_collection_api_collections__name__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections/{name}/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Collection Sample
         * @description Return schema and sample documents for a collection.
         */
        get: operations["collection_sample_api_collections__name__sample_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/blocking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recommend Blocking
         * @description Get blocking key recommendations from a profile.
         */
        post: operations["recommend_blocking_api_config_blocking_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Config
         * @description Export a config recommendation as YAML or JSON.
         */
        post: operations["export_config_api_config_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recommend Strategy
         * @description Get strategy recommendations from profile and objectives.
         */
        post: operations["recommend_strategy_api_config_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Variants
         * @description Compare pipeline configurations by simulating variants.
         */
        post: operations["simulate_variants_api_config_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Config
         * @description Validate a pipeline configuration dict and return errors.
         */
        post: operations["validate_config_api_config_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/curation/{collection}/cluster/{key}/remove-member": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Remove Member
         * @description Eject a member from a cluster (suppress its intra-cluster edges).
         */
        post: operations["remove_member_api_curation__collection__cluster__key__remove_member_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/curation/{collection}/cluster/{key}/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Split Cluster
         * @description Split a cluster by suppressing a bridge edge between two members.
         */
        post: operations["split_cluster_api_curation__collection__cluster__key__split_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/curation/{collection}/history/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Curation History
         * @description Return the audit trail (newest first) for a cluster/entity/pair key.
         */
        get: operations["curation_history_api_curation__collection__history__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/curation/{collection}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge Clusters
         * @description Merge two or more clusters by confirming edges between representatives.
         */
        post: operations["merge_clusters_api_curation__collection__merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/curation/{collection}/suspect-clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suspect Clusters
         * @description Pending entries from the cluster repair queue, scoped to this collection.
         */
        get: operations["suspect_clusters_api_curation__collection__suspect_clusters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/{collection}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Clusters
         * @description Export clusters to JSON and CSV files.
         */
        post: operations["export_clusters_api_export__collection__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/{collection}/download/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Export
         * @description Serve an exported file for download.
         */
        get: operations["download_export_api_export__collection__download__filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/golden/{collection}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge Records
         * @description Execute a golden record merge and persist the result.
         */
        post: operations["merge_records_api_golden__collection__merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/golden/{collection}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Merge
         * @description Preview a golden record merge without persisting.
         */
        post: operations["preview_merge_api_golden__collection__preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/golden/{collection}/{entity_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Golden Record
         * @description Retrieve a golden record by key.
         */
        get: operations["get_golden_record_api_golden__collection___entity_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/golden/{collection}/{entity_key}/provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Golden Provenance
         * @description Return source records and provenance for a golden record.
         */
        get: operations["golden_provenance_api_golden__collection___entity_key__provenance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/{collection}/apply-threshold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Threshold
         * @description Persist chosen thresholds to the run config (audited).
         *
         *     Writes ``similarity.threshold`` and/or ``active_learning.low/high_threshold``
         *     into the target pipeline-run config. Because Fellegi-Sunter posteriors are
         *     stored as the edge ``similarity``, the tuner histogram and these thresholds
         *     share one scale — no separate score↔posterior band remap is needed.
         */
        post: operations["apply_threshold_api_metrics__collection__apply_threshold_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/{collection}/boundary-pairs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Boundary Pairs
         * @description Candidate pairs with an edge score within ``window`` of ``score``.
         */
        get: operations["boundary_pairs_api_metrics__collection__boundary_pairs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/{collection}/cluster-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cluster Quality
         * @description Unsupervised per-cluster coherence metrics over the similarity graph.
         */
        get: operations["cluster_quality_api_metrics__collection__cluster_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/{collection}/score-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Score Distribution
         * @description Histogram of non-suppressed similarity-edge scores (for the tuner).
         */
        get: operations["score_distribution_api_metrics__collection__score_distribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/{collection}/threshold-sweep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Threshold Sweep
         * @description Precision/recall/F1 across thresholds for scored edges vs labeled pairs.
         */
        get: operations["threshold_sweep_api_metrics__collection__threshold_sweep_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pipeline History
         * @description Query pipeline run history from _er_pipeline_runs collection.
         */
        get: operations["pipeline_history_api_pipeline_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Pipeline
         * @description Start a pipeline run in the background. Returns a run_id.
         */
        post: operations["run_pipeline_api_pipeline_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/status/{collection}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pipeline Status
         * @description Collection status: document count, edges, clusters.
         */
        get: operations["pipeline_status_api_pipeline_status__collection__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resolve/cross": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Cross Collection
         * @description Cross-collection entity resolution.
         */
        post: operations["resolve_cross_collection_api_resolve_cross_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resolve/{collection}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Entity
         * @description Resolve a record against a collection.
         */
        post: operations["resolve_entity_api_resolve__collection__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/{collection}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Verdicts
         * @description List verdicts from FeedbackStore, filterable by decision status and score range.
         */
        get: operations["list_verdicts_api_review__collection__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/{collection}/batch-verdict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch Verdict
         * @description Apply many verdicts in one call (bulk actions from the review queue).
         *
         *     Each verdict is persisted and applied to the graph exactly like the
         *     single-pair endpoint; results are aggregated and every applied pair writes
         *     its own audit row. Per-pair failures (e.g. lock contention) are reported
         *     without aborting the batch.
         */
        post: operations["batch_verdict_api_review__collection__batch_verdict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/{collection}/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Verdicts Csv
         * @description Export the (filtered) review queue as CSV.
         */
        get: operations["export_verdicts_csv_api_review__collection__export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/{collection}/optimize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Optimize Thresholds
         * @description Trigger threshold optimization using stored feedback.
         */
        post: operations["optimize_thresholds_api_review__collection__optimize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/{collection}/pair/{key_a}/{key_b}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pair Comparison
         * @description Full pair comparison with field-level scoring and document data.
         */
        get: operations["pair_comparison_api_review__collection__pair__key_a___key_b__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/{collection}/pair/{key_a}/{key_b}/verdict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Verdict
         * @description Record a human correction for a pair and apply it to the graph.
         *
         *     The verdict is persisted (for threshold optimization) and then applied:
         *     a ``no_match`` suppresses the similarity edge, a ``match`` confirms it, and
         *     the affected connected component is re-clustered. ``clusters_changed`` lets
         *     the frontend invalidate its cluster caches.
         */
        post: operations["submit_verdict_api_review__collection__pair__key_a___key_b__verdict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/{collection}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verdict Stats
         * @description Verdict counts by decision type.
         */
        get: operations["verdict_stats_api_review__collection__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/{collection}/thresholds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current Thresholds
         * @description Return current low/high thresholds from the most recent optimization.
         */
        get: operations["current_thresholds_api_review__collection__thresholds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spa Fallback
         * @description Serve the SPA index for any non-API path.
         */
        get: operations["spa_fallback__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplyThresholdRequest */
        ApplyThresholdRequest: {
            /** High Threshold */
            high_threshold?: number | null;
            /** Low Threshold */
            low_threshold?: number | null;
            /** Run Id */
            run_id?: string | null;
            /** Threshold */
            threshold?: number | null;
        };
        /** BatchVerdictItem */
        BatchVerdictItem: {
            /** Confidence */
            confidence?: number | null;
            /** Decision */
            decision: string;
            /** Key A */
            key_a: string;
            /** Key B */
            key_b: string;
        };
        /** BatchVerdictRequest */
        BatchVerdictRequest: {
            /** Verdicts */
            verdicts: components["schemas"]["BatchVerdictItem"][];
        };
        /** ClusterGraphResponse */
        ClusterGraphResponse: {
            /** Edges */
            edges: {
                [key: string]: unknown;
            }[];
            /** Nodes */
            nodes: {
                [key: string]: unknown;
            }[];
        };
        /** ConfigBlockingRequest */
        ConfigBlockingRequest: {
            /**
             * Max Composite Size
             * @default 3
             */
            max_composite_size: number;
            /**
             * Max Results
             * @default 20
             */
            max_results: number;
            /** Must Exclude Fields */
            must_exclude_fields?: string[] | null;
            /** Must Include Fields */
            must_include_fields?: string[] | null;
            /** Profile */
            profile: {
                [key: string]: unknown;
            };
            /** Request Id */
            request_id?: string | null;
        };
        /** ConfigExportRequest */
        ConfigExportRequest: {
            /**
             * Format
             * @default json
             */
            format: string;
            /**
             * Include Rationale
             * @default true
             */
            include_rationale: boolean;
            /** Recommendation */
            recommendation: {
                [key: string]: unknown;
            };
            /** Request Id */
            request_id?: string | null;
        };
        /** ConfigRecommendRequest */
        ConfigRecommendRequest: {
            /**
             * Allow Embedding Models
             * @default true
             */
            allow_embedding_models: boolean;
            /**
             * Allow Graph Clustering
             * @default true
             */
            allow_graph_clustering: boolean;
            /** Objective Profile */
            objective_profile: {
                [key: string]: unknown;
            };
            /** Profile */
            profile: {
                [key: string]: unknown;
            };
            /** Request Id */
            request_id?: string | null;
        };
        /** ConfigSimulateRequest */
        ConfigSimulateRequest: {
            /** Objective Profile */
            objective_profile?: {
                [key: string]: unknown;
            } | null;
            /** Request Id */
            request_id?: string | null;
            /** Variants */
            variants: {
                [key: string]: unknown;
            }[];
        };
        /** ConfigValidateRequest */
        ConfigValidateRequest: {
            /** Config */
            config: {
                [key: string]: unknown;
            };
        };
        /** CrossResolveRequest */
        CrossResolveRequest: {
            /** Options */
            options?: {
                [key: string]: unknown;
            } | null;
            /** Source Collection */
            source_collection: string;
            /** Source Fields */
            source_fields: string[];
            /** Target Collection */
            target_collection: string;
            /** Target Fields */
            target_fields: string[];
        };
        /** ExportRequest */
        ExportRequest: {
            /** Cluster Collection */
            cluster_collection?: string | null;
            /** Edge Collection */
            edge_collection?: string | null;
            /**
             * Filename Prefix
             * @default cluster_export
             */
            filename_prefix: string;
            /** Limit */
            limit?: number | null;
            /** Output Dir */
            output_dir?: string | null;
        };
        /** GoldenRecordPreviewRequest */
        GoldenRecordPreviewRequest: {
            /** Entity Keys */
            entity_keys: string[];
            /**
             * Strategy
             * @default most_complete
             */
            strategy: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MergeClustersRequest */
        MergeClustersRequest: {
            /** Cluster Keys */
            cluster_keys: string[];
        };
        /** PipelineRunRequest */
        PipelineRunRequest: {
            /** Config */
            config: {
                [key: string]: unknown;
            };
        };
        /** PipelineRunResponse */
        PipelineRunResponse: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
        };
        /** RemoveMemberRequest */
        RemoveMemberRequest: {
            /** Member Key */
            member_key: string;
        };
        /** ResolveRequest */
        ResolveRequest: {
            /**
             * Confidence Threshold
             * @default 0.8
             */
            confidence_threshold: number;
            /** Fields */
            fields: string[];
            /** Record */
            record: {
                [key: string]: unknown;
            };
            /**
             * Top K
             * @default 10
             */
            top_k: number;
        };
        /** SplitClusterRequest */
        SplitClusterRequest: {
            /** Key A */
            key_a: string;
            /** Key B */
            key_b: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerdictRequest */
        VerdictRequest: {
            /** Confidence */
            confidence?: number | null;
            /** Decision */
            decision: string;
            /** Notes */
            notes?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_clusters_api_clusters__collection__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                min_size?: number;
            };
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cluster_stats_api_clusters__collection__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cluster_detail_api_clusters__collection___key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cluster_graph_api_clusters__collection___key__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterGraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_collections_api_collections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    profile_collection_api_collections__name__profile_get: {
        parameters: {
            query?: {
                sample_limit?: number;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    collection_sample_api_collections__name__sample_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_blocking_api_config_blocking_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigBlockingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_config_api_config_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_strategy_api_config_recommend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigRecommendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_variants_api_config_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigSimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_config_api_config_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_curation__collection__cluster__key__remove_member_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    split_cluster_api_curation__collection__cluster__key__split_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SplitClusterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    curation_history_api_curation__collection__history__key__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                collection: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_clusters_api_curation__collection__merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeClustersRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suspect_clusters_api_curation__collection__suspect_clusters_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_clusters_api_export__collection__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_export_api_export__collection__download__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_records_api_golden__collection__merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoldenRecordPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_merge_api_golden__collection__preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoldenRecordPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_golden_record_api_golden__collection___entity_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
                entity_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    golden_provenance_api_golden__collection___entity_key__provenance_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
                entity_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    apply_threshold_api_metrics__collection__apply_threshold_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyThresholdRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    boundary_pairs_api_metrics__collection__boundary_pairs_get: {
        parameters: {
            query: {
                score: number;
                window?: number;
                limit?: number;
            };
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cluster_quality_api_metrics__collection__cluster_quality_get: {
        parameters: {
            query?: {
                min_coherence?: number;
            };
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_distribution_api_metrics__collection__score_distribution_get: {
        parameters: {
            query?: {
                bucket?: number;
            };
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    threshold_sweep_api_metrics__collection__threshold_sweep_get: {
        parameters: {
            query: {
                /** @description Ground-truth pair collection. */
                truth_collection: string;
                /** @description Optional comma-separated threshold grid (else exact curve). */
                thresholds?: string | null;
            };
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pipeline_history_api_pipeline_history_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_pipeline_api_pipeline_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pipeline_status_api_pipeline_status__collection__get: {
        parameters: {
            query?: {
                edge_collection?: string | null;
            };
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_cross_collection_api_resolve_cross_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrossResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_entity_api_resolve__collection__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_verdicts_api_review__collection__get: {
        parameters: {
            query?: {
                status?: string | null;
                min_score?: number | null;
                max_score?: number | null;
                source?: string | null;
                sort_by?: string;
                sort_order?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_verdict_api_review__collection__batch_verdict_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchVerdictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_verdicts_csv_api_review__collection__export_csv_get: {
        parameters: {
            query?: {
                status?: string | null;
                source?: string | null;
                min_score?: number | null;
                max_score?: number | null;
            };
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimize_thresholds_api_review__collection__optimize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pair_comparison_api_review__collection__pair__key_a___key_b__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
                key_a: string;
                key_b: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_verdict_api_review__collection__pair__key_a___key_b__verdict_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
                key_a: string;
                key_b: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerdictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verdict_stats_api_review__collection__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_thresholds_api_review__collection__thresholds_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spa_fallback__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
