import { useState } from "react";
import { Trophy, ArrowRight, Loader2, Save, Check } from "lucide-react";
import { Link } from "react-router-dom";
import { EmptyState } from "../components/shared/EmptyState";
import { useSelectedCollection } from "../contexts/CollectionContext";
import { GoldenRecordView } from "../components/golden/GoldenRecordView";
import { MergeStrategySelector } from "../components/golden/MergeStrategySelector";
import {
  survivorshipPreview,
  applyGoldenRecord,
  type FieldProvenance,
} from "../api/golden";

export function GoldenRecordsPage() {
  const { selectedCollection } = useSelectedCollection();
  const [keysInput, setKeysInput] = useState("");
  const [strategy, setStrategy] = useState("field_voting");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [preview, setPreview] = useState<{
    fields: Record<string, unknown>;
    provenance: Record<string, { source: string; confidence: number }>;
    conflicts: string[];
    sources: Record<string, unknown>[];
    memberKeys: string[];
  } | null>(null);

  if (!selectedCollection) {
    return (
      <EmptyState
        icon={Trophy}
        title="No collection selected"
        description="Select a collection from the sidebar to manage golden records."
      />
    );
  }

  const parsedKeys = keysInput
    .split(",")
    .map((k) => k.trim())
    .filter(Boolean);

  async function handlePreview() {
    if (parsedKeys.length < 2) return;
    setLoading(true);
    setError(null);
    setPreview(null);
    setSaved(false);

    try {
      const result = await survivorshipPreview(
        selectedCollection!,
        parsedKeys,
        strategy,
      );
      // Adapt engine provenance ({chosenFrom, strategy, ...}) to the view's
      // {source, confidence} shape.
      const prov: Record<string, { source: string; confidence: number }> = {};
      for (const [f, p] of Object.entries(
        (result.provenance ?? {}) as Record<string, FieldProvenance>,
      )) {
        prov[f] = { source: p.chosenFrom, confidence: 0 };
      }
      setPreview({
        fields: { ...result.golden_record },
        provenance: prov,
        conflicts: result.conflicts ?? [],
        sources: result.sources ?? [],
        memberKeys: result.merged_keys ?? parsedKeys,
      });
    } catch (err) {
      setError(err instanceof Error ? err.message : "Preview failed");
    } finally {
      setLoading(false);
    }
  }

  function handleResolveConflict(field: string, value: unknown) {
    setPreview((prev) =>
      prev ? { ...prev, fields: { ...prev.fields, [field]: value } } : prev,
    );
    setSaved(false);
  }

  async function handleApply() {
    if (!preview) return;
    setSaving(true);
    setError(null);
    try {
      await applyGoldenRecord(
        selectedCollection!,
        preview.memberKeys,
        preview.fields,
        strategy,
      );
      setSaved(true);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Save failed");
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-lg font-semibold text-gray-900">Golden Records</h1>
        <p className="mt-1 text-sm text-gray-500">
          Golden records are generated by merging cluster members into a single
          canonical entity. Enter entity keys below to preview a merged record,
          or browse clusters to select records.
        </p>
      </div>

      <div className="rounded-lg border border-gray-200 bg-white p-6">
        <div className="space-y-4">
          <div>
            <label className="mb-1 block text-sm font-medium text-gray-700">
              Entity Keys
            </label>
            <input
              type="text"
              value={keysInput}
              onChange={(e) => setKeysInput(e.target.value)}
              placeholder="key1, key2, key3"
              className="block w-full rounded-md border border-gray-300 px-3 py-2 text-sm shadow-sm placeholder:text-gray-400 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500"
            />
            <p className="mt-1 text-xs text-gray-500">
              Comma-separated list of record keys from{" "}
              <span className="font-medium">{selectedCollection}</span>
            </p>
          </div>

          <div className="max-w-xs">
            <MergeStrategySelector value={strategy} onChange={setStrategy} />
          </div>

          <div className="flex items-center gap-4">
            <button
              onClick={handlePreview}
              disabled={loading || parsedKeys.length < 2}
              className="inline-flex items-center gap-2 rounded-md bg-indigo-600 px-4 py-2.5 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 disabled:opacity-50"
            >
              {loading ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Trophy className="h-4 w-4" />
              )}
              {loading ? "Generating…" : "Preview Golden Record"}
            </button>

            <Link
              to="/clusters"
              className="inline-flex items-center gap-1 text-sm text-indigo-600 hover:text-indigo-800"
            >
              Or browse clusters to select records
              <ArrowRight className="h-3.5 w-3.5" />
            </Link>
          </div>
        </div>
      </div>

      {error && (
        <div className="rounded-md bg-red-50 px-4 py-3 text-sm text-red-700">
          {error}
        </div>
      )}

      {preview && (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-semibold text-gray-900">
              Preview Result
              {preview.conflicts.length > 0 && (
                <span className="ml-2 rounded bg-amber-100 px-2 py-0.5 text-xs font-medium text-amber-800">
                  {preview.conflicts.length} conflicting field
                  {preview.conflicts.length === 1 ? "" : "s"}
                </span>
              )}
            </h2>
            <button
              onClick={handleApply}
              disabled={saving}
              className="inline-flex items-center gap-2 rounded-md bg-green-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-green-700 disabled:opacity-50"
            >
              {saving ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : saved ? (
                <Check className="h-4 w-4" />
              ) : (
                <Save className="h-4 w-4" />
              )}
              {saved ? "Saved" : "Save golden record"}
            </button>
          </div>
          <p className="text-xs text-gray-500">
            Click a conflicting field (amber) to pick a different source value before saving.
          </p>
          <GoldenRecordView
            goldenRecord={preview.fields}
            provenance={preview.provenance}
            conflicts={preview.conflicts}
            sources={preview.sources}
            onResolveConflict={handleResolveConflict}
          />
        </div>
      )}
    </div>
  );
}
