import { useState } from "react";
import { Trophy, ArrowRight, Loader2 } from "lucide-react";
import { Link } from "react-router-dom";
import { EmptyState } from "../components/shared/EmptyState";
import { useSelectedCollection } from "../contexts/CollectionContext";
import { GoldenRecordView } from "../components/golden/GoldenRecordView";
import { MergeStrategySelector } from "../components/golden/MergeStrategySelector";
import { previewGoldenRecord } from "../api/golden";

export function GoldenRecordsPage() {
  const { selectedCollection } = useSelectedCollection();
  const [keysInput, setKeysInput] = useState("");
  const [strategy, setStrategy] = useState("most_complete");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [preview, setPreview] = useState<{
    fields: Record<string, unknown>;
    provenance: Record<string, { source: string; confidence: number }>;
    conflicts: string[];
  } | null>(null);

  if (!selectedCollection) {
    return (
      <EmptyState
        icon={Trophy}
        title="No collection selected"
        description="Select a collection from the sidebar to manage golden records."
      />
    );
  }

  const parsedKeys = keysInput
    .split(",")
    .map((k) => k.trim())
    .filter(Boolean);

  async function handlePreview() {
    if (parsedKeys.length === 0) return;
    setLoading(true);
    setError(null);
    setPreview(null);

    try {
      const result = await previewGoldenRecord(
        selectedCollection!,
        parsedKeys,
        strategy,
      );

      // The merge preview returns the fused golden record. Field-level
      // provenance/conflicts are not produced by the preview endpoint, so they
      // render empty until a richer survivorship API exists.
      const goldenFields = (result.golden_record ?? {}) as Record<string, unknown>;

      setPreview({
        fields: goldenFields,
        provenance: {},
        conflicts: [],
      });
    } catch (err) {
      setError(err instanceof Error ? err.message : "Preview failed");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-lg font-semibold text-gray-900">Golden Records</h1>
        <p className="mt-1 text-sm text-gray-500">
          Golden records are generated by merging cluster members into a single
          canonical entity. Enter entity keys below to preview a merged record,
          or browse clusters to select records.
        </p>
      </div>

      <div className="rounded-lg border border-gray-200 bg-white p-6">
        <div className="space-y-4">
          <div>
            <label className="mb-1 block text-sm font-medium text-gray-700">
              Entity Keys
            </label>
            <input
              type="text"
              value={keysInput}
              onChange={(e) => setKeysInput(e.target.value)}
              placeholder="key1, key2, key3"
              className="block w-full rounded-md border border-gray-300 px-3 py-2 text-sm shadow-sm placeholder:text-gray-400 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500"
            />
            <p className="mt-1 text-xs text-gray-500">
              Comma-separated list of record keys from{" "}
              <span className="font-medium">{selectedCollection}</span>
            </p>
          </div>

          <div className="max-w-xs">
            <MergeStrategySelector value={strategy} onChange={setStrategy} />
          </div>

          <div className="flex items-center gap-4">
            <button
              onClick={handlePreview}
              disabled={loading || parsedKeys.length === 0}
              className="inline-flex items-center gap-2 rounded-md bg-indigo-600 px-4 py-2.5 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 disabled:opacity-50"
            >
              {loading ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Trophy className="h-4 w-4" />
              )}
              {loading ? "Generating…" : "Preview Golden Record"}
            </button>

            <Link
              to="/clusters"
              className="inline-flex items-center gap-1 text-sm text-indigo-600 hover:text-indigo-800"
            >
              Or browse clusters to select records
              <ArrowRight className="h-3.5 w-3.5" />
            </Link>
          </div>
        </div>
      </div>

      {error && (
        <div className="rounded-md bg-red-50 px-4 py-3 text-sm text-red-700">
          {error}
        </div>
      )}

      {preview && (
        <div className="space-y-4">
          <h2 className="text-sm font-semibold text-gray-900">
            Preview Result
          </h2>
          <GoldenRecordView
            goldenRecord={preview.fields}
            provenance={preview.provenance}
            conflicts={preview.conflicts}
          />
        </div>
      )}
    </div>
  );
}
